project_id = "khcuvryopmaemccrptlk"

[functions.refresh-markets]
verify_jwt = false

[functions.generate-ai-predictions]
verify_jwt = false

[functions.evaluate-predictions]
verify_jwt = false

[functions.generate-predictions-free]
verify_jwt = false

[functions.generate-predictions-basic]
verify_jwt = false

[functions.generate-predictions-premium]
verify_jwt = false

[functions.fetch-crypto-sentiment]
verify_jwt = false